project:
  type: website
  output-dir: docs

website:
  title: "Laurent Rouvière"
#  navbar:
#    background: primary
#    left:
#      - href: index.qmd
#        text: Home
#      - about.qmd
  sidebar: 
    style: "docked"
    search: true
    background: orange
    collapse-level: 3
#    foreground: red
    contents:
      - index.qmd
#      - section: "CV"
#        contents:
#          - index.qmd
      - section: "Enseignements"
        contents:
          - enseignement.qmd
          - section: "Supports de cours"
            contents: 
              - apprentissage_sup.qmd
              - visualisationR.qmd
              - grande_dim.qmd
              - autres_cours.qmd
      - section: "Recherche"
        contents:
          - livres.qmd
          - articles.qmd

lang: fr

format:
  html:
    backgroundcolor: white
    theme: 
      - united
#      - darkly
#      - custom.scss
    css: styles.css
    page-layout: full
    linkcolor: red
    link-external-newwindow: true
    fontsize: 12pt
    cite-method: citeproc
    biblio-style: apalike
    biblio-title: "Arti"
#    page-layout: full
#    max-width: 18em

editor: visual

