---
title: "Apprentissage supervisé - Machine learning"
---

Ce cours est dispensé dans différentes formations de niveau Master, ainsi qu'en formation continue. Les notions suivantes sont abordées :

-   **Notions de risque et calcul de risque en apprentissage supervisé**, fonction de perte, méthodes de ré-échantillonnage (hold-out, validation croisée)
-   **Algorithmes linéaires**
    -   Moindres carrés ordinaires
    -   Sélection de variables
    -   Régularisation : ridge, lasso...
    -   Support vector machine : cas séparable, non séparable et astuce du noyau
-   **Algorithmes non linéaires**
    -   Arbres, notamment l'algorithme CART
    -   Réseaux de neurones : perceptron multicouches avec `keras`
-   **Agrégation**
    -   Forêts aléatoires
    -   Gradient boosting

**Supports complet**

-   [slides](docs/machine_learning/cours.pdf)
-   [slides au format rapport](docs/machine_learning/cours_article.pdf) (pour impression)
-   [tutoriel sans corrigés](https://lrouviere.github.io/TUTO_ML), [codes R associés](docs/machine_learning/codes_sans_cor.R)
-   [tutoriel avec corrigés](https://lrouviere.github.io/TUTO_ML/correction) (pas toujours disponible), [code R associés](docs/machine_learning/codes_avec_cor.R)

------------------------------------------------------------------------

### Cours d'apprentissage supervisé en M1 MAS

Cette partie est restreinte à une introduction à l'apprentissage supervisé. On y présente les fondamentaux sur le risque en machine learning ainsi que quelques algorithmes de référence :

-   **Notions de risque et calcul de risque en apprentissage supervisé**, fonction de perte, méthodes de ré-échantillonnage (hold-out, validation croisée)
-   **Méthodes par arbres** : algorithmes CART et forêts aléatoires

**Supports** :

-   [slides](docs/machine_learning/cours_app_sup_R2.pdf)

-   [slides au format rapport](docs//machine_learning/cours_app_sup_R2_article.pdf)

-   [tutoriel](https://lrouviere.github.io/TUTO_ML) (chapitres 1, 3 et 5)

------------------------------------------------------------------------

### Formation continue

-   Partie cours
    -   [slides complet](docs/machine_learning/cours_cepe_intro_ml.pdf)
    -   [slides au format rapport](docs/machine_learning/cours_article_cepe_intro_ml.pdf)
-   Tutoriel
    -   [version non corrigée](docs/machine_learning/tuto_court_ml_sans_correc.html){.illustration}
    -   [version corrigée](docs/machine_learning/tuto_court_ml_avec_correc.html), [en pdf](docs/machine_learning/tuto_court_ml.pdf)
    -   [codes R](docs/machine_learning/tuto_court_ml.R)
    -   [données ozone](docs/machine_learning/ozone.txt)
