---
title: "Présentation"
---

## Cours actuels à l'Université Rennes 2

### [Licence Miashs](https://sites-formations.univ-rennes2.fr/licence-miashs/)

-   Introduction au machine learning en L1 (12h CM - 12h TD)

-   Statistique inférentielle en L3 (24h CM - 24h TD)

### [Master Mathématiques Appliquées, Statistique](https://sites-formations.univ-rennes2.fr/master-mas/)

-   [Apprentissage statistique en M1](apprentissage_sup.qmd#app-sup-M1MAS){style="color: green"} (16h CM - 8h TD)

-   Visualisation des données en M1 (24h TD)

-   Statistique en grande dimension en M2 (16h CM - 8h TD)

------------------------------------------------------------------------

## Cours dans d'autres formations

-   *Compléments de machine learning* (notamment les SVM) et *Introduction aux graphes* dans le Master Data Science de l'Institut National Polytechnique Félix Houphouët Boiny à Yamoussoukro (Côte d'Ivoire)

-   *Dynamic data visualization* dans le MSC Statistics for smart data à l'Ensai

-   [Statistique avec R](visualisationR.qmd#visuR-staps-ens){style="color: green"} dans le Magistère Sciences du Sport et Education Physique à l'ENS Rennes
