---
title: "Fonctions et CV"
---

Maître de conférences à l'[Université Rennes 2](https://www.univ-rennes2.fr)

## Coordonnées

Université Rennes 2, Département Miashs\
Place du recteur Henri le Moal, CS 24307\
35 043 Rennes cedex

*Téléphone :* 02 99 14 18 06\
*Email* : laurent.rouviere\@univ-rennes2.fr

## Fonctions et responsabilités

-   Enseignant chercheur en Mathématiques Appliquées, affilié au [département MIASHS](http://www.univ-rennes2.fr/mass) et à la composante Rennes 2 de l'[équipe de Statistique de l'IRMAR](http://irmar.univ-rennes1.fr/Equipes/aleatoire/Statistique/).

-   Co-responsable du [Master Mathématiques Appliquées, Statistique (MAS)](https://sites-formations.univ-rennes2.fr/master-mas/), Universités de Rennes 1 et Rennes 2, Agrocampus Ouest, Ensai, INSA Rennes

-   Responsable du parcours [Science des données, Intelligence Artificielle du Master MAS](https://sites-formations.univ-rennes2.fr/master-mas/components/formation/m2-rennes2.html), Université Rennes 2.

## Parcours

+-------------+------------------------------------------------------------------------------------------------------------------------------------+
| 2006 - ...  | **Maître de Conférences**, *Université Rennes 2*                                                                                   |
|             |                                                                                                                                    |
|             | Détachement sur un poste d'**enseignant chercheur** à l'*Ensai* entre 2009 et 2015                                                 |
+-------------+------------------------------------------------------------------------------------------------------------------------------------+
| 2005 - 2006 | **ATER**, *Université Rennes 2*                                                                                                    |
+-------------+------------------------------------------------------------------------------------------------------------------------------------+
| 2002 - 2005 | **Doctorat** de Mathématiques Appliquées, *Université Montpellier 2*                                                               |
|             |                                                                                                                                    |
|             | -   *Titre* : Estimation de densité en dimension élevée et classification de courbes                                               |
|             |                                                                                                                                    |
|             | -   *Directeurs de thèse* : Alain Berlinet (Professeur, Université Montpellier 2) et Gérard Biau (Professeur, Sorbonne Université) |
+-------------+------------------------------------------------------------------------------------------------------------------------------------+

[Télécharger mon cv complet](docs/cv_LR.pdf)
